### ISSUE TITLE
Dodać komendę Queue do edycji kolejki

### ISSUE THREAD

**Issue by atawizmmocno** [WKK-Offcial/wkk_discord_bot#17]
JW

**Comment by ShootGan** [comment]
Ale w sumie po co skoro rzeczy dodają się automatycznie do kolejki na /play a sama kolejka tego co będzie grane jest wyświetlane w embedzie który zawsze jest na samym dole chaty utrzymywany.

**Comment by PiotrWieczorek98** [comment]
> Ale w sumie po co skoro rzeczy dodają się automatycznie do kolejki na /play a sama kolejka tego co będzie grane jest wyświetlane w embedzie który zawsze jest na samym dole chaty utrzymywany.

Też tak myśle, ale przyszłościowo można zrobić edytowanie kolejki z takiej komendy

**Comment by Rakkuzan** [comment]
2ae47067 dodał możliwość wybierania co ma grac z kolejki.
Zamknij jak takie coś jest wystarczające

**Comment by PiotrWieczorek98** [comment]
Może być
